# Generated by Django 5.1.1 on 2024-09-10 15:25

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=70, unique=True, verbose_name="name")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from="title", unique_with=["created_at"])),
                ("meta_title", models.CharField(max_length=100, unique=True, verbose_name="Meta Title")),
                ("body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, unique=True, verbose_name="Title")),
                ("meta_title", models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="Meta Title")),
                ("body", models.TextField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=300, null=True)),
                ("image", models.ImageField(blank=True, default="default.png", null=True, upload_to="uploads/", verbose_name="Post image")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from="title", unique_with=["publish_date"])),
                ("publish_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("categories", models.ManyToManyField(blank=True, to="blog.category")),
                ("owner", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("approved_comment", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.post")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=70, unique=True, verbose_name="name")),
                ("slug", autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from="title", unique_with=["created_at"])),
                ("meta_title", models.CharField(max_length=100, unique=True, verbose_name="title")),
                ("body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
